import React from "react";
const columns = [
  { name: "ITEM", uid: "item" },
  { name: "POSTING SCHEDULE", uid: "postingschedule" },
  { name: "POSTING TIME", uid: "postingtime" },
  { name: "LEAD", uid: "lead" },
  { name: "CONTENT CATEGORY", uid: "contentcategory" },
  { name: "CONTENT TEXT LINK", uid: "contenttextlink" },
  { name: "CONTENT TEXT", uid: "contenttext" },
  { name: "CONTENT POSTING", uid: "contentposting" },
  { name: "POSTING CAPTION", uid: "postingcaption" },
  { name: "INSTAGRAM POSTING STATUS", uid: "instagrampostingstatus" },
  { name: "TIKTOK POSTING STATUS", uid: "tiktokpostingstatus" },
  { name: "LAST UPDATED", uid: "lastupdated" },
  // {name: "NAME", uid: "name"},
  { name: "ROLE", uid: "role" },
  { name: "STATUS", uid: "status" },
  { name: "ACTIONS", uid: "actions" },
];

const users = [
  {
    id: 1,
    lead: "Tony Reichert",
    role: "CEO",
    team: "Management",
    status: "active",
    age: "29",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
    item: "Video cara masak nashville",
    postingschedule: "7 Nov",
    postingtime: "19:00",
    contentcategory: "reels",
    contenttextlink: "www.google.com",
    contenttext: "TEXT FILE",
    contentposting: "file yang akan diposting",
    postingcaption: "Lorem ipsum dolor sit, amet consectetur adipisicing elit",
    instagrampostingstatus: "posted",
    tiktokpostingstatus: "posted",
    lastupdated: "Gilbran",
  },
  {
    id: 2,
    lead: "Zoey Lang",
    role: "Technical Lead",
    team: "Development",
    status: "paused",
    age: "25",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
    item: "Video cara masak nashville",
    postingschedule: "7 Nov",
    postingtime: "19:00",
    contentcategory: "tiktok",
    contenttextlink: "www.google.com",
    contenttext: "TEXT FILE",
    contentposting: "file yang akan diposting",
    postingcaption: "Lorem ipsum dolor sit, amet consectetur adipisicing elit",
    instagrampostingstatus: "on hold",
    tiktokpostingstatus: "on hold",
    lastupdated: "Gilbran",
  },
  {
    id: 3,
    lead: "Jane Fisher",
    role: "Senior Developer",
    team: "Development",
    status: "active",
    age: "22",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
    item: "Video cara masak nashville",
    postingschedule: "7 Nov",
    postingtime: "19:00",
    contentcategory: "design",
    contenttextlink: "www.google.com",
    contenttext: "TEXT FILE",
    contentposting: "file yang akan diposting",
    postingcaption: "Lorem ipsum dolor sit, amet consectetur adipisicing elit",
    instagrampostingstatus: "not yet posted",
    tiktokpostingstatus: "not yet posted",
    lastupdated: "Gilbran",
  },
  {
    id: 4,
    lead: "William Howard",
    role: "Community Manager",
    team: "Marketing",
    status: "vacation",
    age: "28",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
    item: "Video cara masak nashville",
    postingschedule: "7 Nov",
    postingtime: "19:00",
    contentcategory: "photo",
    contenttextlink: "www.google.com",
    contenttext: "TEXT FILE",
    contentposting: "file yang akan diposting",
    postingcaption: "Lorem ipsum dolor sit, amet consectetur adipisicing elit",
    instagrampostingstatus: "on preview",
    tiktokpostingstatus: "on preview",
    lastupdated: "Gilbran",
  },
  {
    id: 5,
    lead: "Kristen Copper",
    role: "Sales Manager",
    team: "Sales",
    status: "active",
    age: "24",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
    item: "Video cara masak nashville",
    postingschedule: "7 Nov",
    postingtime: "19:00",
    contentcategory: "education",
    contenttextlink: "www.google.com",
    contenttext: "TEXT FILE",
    contentposting: "file yang akan diposting",
    postingcaption: "Lorem ipsum dolor sit, amet consectetur adipisicing elit",
    instagrampostingstatus: "posted",
    tiktokpostingstatus: "posted",
    lastupdated: "Gilbran",
  },
];

export { columns, users };
